name: Construir
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  construir:
    name: Construir Interfaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Tags
        uses: mosfetlang/dev-tagger-action@v1
        with:
          tag-prefix: "Patito-"
