name: Construir
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  construir:
    name: Construir Interfaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Tags
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: Quesadilla
          custom_tag: Patito1
          release_branches: master
