name: Construir
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  construir:
    name: Construir Interfaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Tags
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "Quesadilla"
